// lib/db/mock-activities.ts

export interface Activity {
  id: string;
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  creditCost: number; 
  maxParticipants: number; 
  currentParticipants: number; 
  rating: number;
  reviewCount: number;
  reviews: number; 
  locationName: string; 
  imageUrl: string;
  category: string;
  durationHours: number;
  currency: string;
}

export const mockActivities: Activity[] = [
  {
    id: '1',
    name: 'Golf Round at Frankfurter Golf Club',
    description: 'Enjoy a round of golf at the prestigious Frankfurter Golf Club. Limited spots available.',
    latitude: 50.074271200118424, 
    longitude: 8.634918624921484, 
    creditCost: 25, 
    maxParticipants: 4, 
    currentParticipants: 2, 
    rating: 4.8,
    reviewCount: 25,
    reviews: 25,
    locationName: 'Frankfurter Golf Club', 
    imageUrl: '/assets/images/5cd56052608c7d0007c27dae.jpg', 
    category: 'Sports',
    durationHours: 4,
    currency: 'EUR',
  },
  {
    id: '2',
    name: 'Main Tower Observation Deck Visit',
    description: 'Get breathtaking panoramic views of Frankfurt from the Main Tower.',
    latitude: 50.1138, 
    longitude: 8.6736, 
    creditCost: 10, 
    maxParticipants: 15, 
    currentParticipants: 7, 
    rating: 4.96,
    reviewCount: 152,
    reviews: 152,
    locationName: 'Main Tower, Frankfurt', 
    imageUrl: '/assets/images/main-tower-besucherterrasse-2022.jpg', 
    category: 'Sightseeing',
    durationHours: 3,
    currency: 'EUR',
  },
  {
    id: '3',
    name: 'Aperol & Friends',
    description: 'Enjoy some refreshing Aperol Spritz with friends in Sachsenhausen.',
    latitude: 50.1040, 
    longitude: 8.6890, 
    creditCost: 15, 
    maxParticipants: 10, 
    currentParticipants: 9, 
    rating: 4.8, 
    reviewCount: 98, 
    reviews: 98,
    locationName: 'Sachsenhausen, Frankfurt', 
    imageUrl: '/assets/images/close-up-of-a-female-hands-with-glasses-with-a-del-2025-01-09-18-36-55-utc.jpg', 
    category: 'Speisen und Getränke',
    durationHours: 3,
    currency: 'EUR',
  },
  {
    id: '4',
    name: 'Relaxing Stroll in Palmengarten',
    description: 'Explore the beautiful botanical gardens of Frankfurt.',
    latitude: 50.1207, 
    longitude: 8.6587, 
    creditCost: 3, 
    maxParticipants: 25, 
    currentParticipants: 22, 
    rating: 4.88,
    reviewCount: 115,
    reviews: 115,
    locationName: 'Palmengarten, Frankfurt', 
    imageUrl: 'https://images.unsplash.com/photo-1550355191-94b32f5c8f4a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'Nature',
    durationHours: 4,
    currency: 'EUR',
  },
  {
    id: '5',
    name: 'Padel Match near Grüneburgpark',
    description: 'Join an exciting game of Padel tennis at a court near the park.',
    latitude: 50.138548848127975, 
    longitude: 8.63948664212504, 
    creditCost: 12, 
    maxParticipants: 4, 
    currentParticipants: 3, 
    rating: 4.7, 
    reviewCount: 35, 
    reviews: 35,
    locationName: 'Padel Court Ginnheim/Bockenheim', 
    imageUrl: '/assets/images/auch-bei-den-deutschen-beliebt.webp', 
    category: 'Sports',
    durationHours: 1.5, 
    currency: 'EUR',
  },
  {
    id: '6',
    name: 'Museumsufer Exploration',
    description: 'Visit some of the diverse museums along the banks of the Main river.',
    latitude: 50.1072, 
    longitude: 8.6810, 
    creditCost: 12, 
    maxParticipants: 12, 
    currentParticipants: 5, 
    rating: 4.75,
    reviewCount: 45,
    reviews: 45,
    locationName: 'Museumsufer, Frankfurt', 
    imageUrl: 'https://images.unsplash.com/photo-1591309147049-f7c669e6a4f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'Culture',
    durationHours: 2.5,
    currency: 'EUR',
  },
  {
    id: '7',
    name: 'Städel Museum Visit',
    description: 'Explore masterpieces from the Old Masters to contemporary art.',
    latitude: 50.1043, 
    longitude: 8.6759, 
    creditCost: 18,
    maxParticipants: 30, 
    currentParticipants: 15,
    rating: 4.8,
    reviewCount: 160,
    reviews: 160,
    locationName: 'Städel Museum, Frankfurt',
    imageUrl: 'https://images.unsplash.com/photo-1587471071217-71c072b4f6f8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'Culture',
    durationHours: 3,
    currency: 'EUR',
  },
  {
    id: '8',
    name: 'Goethe House and Museum Tour',
    description: 'Visit the birthplace of Germany\'s most famous writer, Johann Wolfgang von Goethe.',
    latitude: 50.1130, 
    longitude: 8.6797, 
    creditCost: 10,
    maxParticipants: 15,
    currentParticipants: 11,
    rating: 4.7,
    reviewCount: 85,
    reviews: 85,
    locationName: 'Goethe House, Frankfurt',
    imageUrl: 'https://images.unsplash.com/photo-1560010267-94b32f5c8f4a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'History',
    durationHours: 2,
    currency: 'EUR',
  },
  {
    id: '9',
    name: 'Shopping on Berger Straße',
    description: 'Explore the boutiques, cafes, and atmosphere of this popular shopping street.',
    latitude: 50.1219, 
    longitude: 8.7027, 
    creditCost: 2, 
    maxParticipants: 50, 
    currentParticipants: 30,
    rating: 4.6,
    reviewCount: 65,
    reviews: 65,
    locationName: 'Berger Straße, Bornheim',
    imageUrl: 'https://images.unsplash.com/photo-1513023879106-f7dec939d8a7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'Shopping',
    durationHours: 2.5,
    currency: 'EUR',
  },
  {
    id: '10',
    name: 'Main River Cruise',
    description: 'See the Frankfurt skyline from a different perspective on a relaxing boat tour.',
    latitude: 50.1083, 
    longitude: 8.6790, 
    creditCost: 20,
    maxParticipants: 40,
    currentParticipants: 25,
    rating: 4.7,
    reviewCount: 130,
    reviews: 130,
    locationName: 'Mainkai, Frankfurt',
    imageUrl: 'https://images.unsplash.com/photo-1557160369-f7c669e6a4f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'Tour',
    durationHours: 1.5,
    currency: 'EUR',
  },
  {
    id: '11',
    name: 'Food Tasting at Kleinmarkthalle',
    description: 'Sample local delicacies and fresh produce in this vibrant indoor market.',
    latitude: 50.1127, 
    longitude: 8.6839, 
    creditCost: 8,
    maxParticipants: 20,
    currentParticipants: 18,
    rating: 4.9,
    reviewCount: 175,
    reviews: 175,
    locationName: 'Kleinmarkthalle, Frankfurt',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'Speisen und Getränke',
    durationHours: 1,
    currency: 'EUR',
  },
  {
    id: '12',
    name: 'Picnic in Grüneburgpark',
    description: 'Enjoy a relaxing afternoon in one of Frankfurt\'s largest and most beautiful parks.',
    latitude: 50.1277, 
    longitude: 8.6615, 
    creditCost: 1, 
    maxParticipants: 100, 
    currentParticipants: 40,
    rating: 4.6,
    reviewCount: 55,
    reviews: 55,
    locationName: 'Grüneburgpark, Westend',
    imageUrl: 'https://images.unsplash.com/photo-1560621608-08a5d749c31c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', 
    category: 'Nature',
    durationHours: 3,
    currency: 'EUR',
  },
  // Add Co-founder wanted 6.0 event
  {
    id: '13',
    name: 'Co-founder wanted 6.0',
    description: '6th Edition event connecting founders, business minds, and tech talent from multiple universities. Pitch ideas, join teams, and network. Two-day agenda with pitching, teambuilding, coaching, and networking.',
    latitude: 50.132902243864, 
    longitude: 8.680153966769781, 
    creditCost: 1, 
    maxParticipants: 150, 
    currentParticipants: 75, 
    rating: 4.7,
    reviewCount: 5, 
    reviews: 5,
    locationName: 'Frankfurt School of Finance & Management', 
    imageUrl: '/assets/images/CFW_08-09.05.2025.png', 
    category: 'Networking',
    durationHours: 12, 
    currency: 'EUR',
  },
];
